spring:
  datasource:
    url: jdbc:mysql://localhost:3306/un_sec?useSSL=false&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 9091
  servlet:
    context-path: /api

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger{36} - %msg%n"

feign:
  protocol: http